// File: test_random.v
// Generated by MyHDL 0.10
// Date: Sat Aug  4 11:13:33 2018


`timescale 1ns/10ps

module test_random (
    c,
    l
);


output c;
reg c;
output [0:0] l;
wire [0:0] l;

reg [2:0] blink0_clk_cnt;
reg blink0_strobe;
reg [0:0] blink0_led_mem;



always @(posedge c) begin: TEST_RANDOM_BLINK0_BEH_STROBE
    if (($signed({1'b0, blink0_clk_cnt}) >= (5 - 1))) begin
        blink0_clk_cnt <= 0;
        blink0_strobe <= (!blink0_strobe);
        if (blink0_strobe) begin
            blink0_led_mem <= 0;
            $write("%h", $time);
            $write(" change!");
            $write("%h", str(blink0_led_mem));
            $write("\n");
        end
        else begin
            blink0_led_mem <= (2 - 1);
            $write("%h", $time);
            $write(" change!");
            $write("%h", str(blink0_led_mem));
            $write("\n");
        end
    end
    else begin
        blink0_clk_cnt <= (blink0_clk_cnt + 1);
    end
end



assign l = blink0_led_mem;


initial begin: TEST_RANDOM_CLKDRIVER0_DRIVE_CLK
    while (1'b1) begin
        # 5;
        c <= 1;
        # 5;
        c <= 0;
    end
end

endmodule
